###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "Jason Saul",
    "password": "password",
    "email": "jason.guerra253@gmail.com"
}


###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "password": "password",
    "username": "jason.guerra253@gmail.com"
}


### 
GET http://localhost:8080/tipoProducto
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqYXNvbi5ndWVycmEyNTNAZ21haWwuY29tIiwic2NvcGUiOiJVU0VSIiwiaXNzIjoiIiwiZXhwIjoxNzQyNTI1NzM0LCJpYXQiOjE3NDI1MjIxMzQsInVzZXJuYW1lIjoiamFzb24uZ3VlcnJhMjUzQGdtYWlsLmNvbSJ9.P3U4BGYvrjtfqfExuy7lW0lbnXeKKG7u0acpwE6SVuww_HGN93gh9aWAC3aTCbXKtcZTjpQ6CaGGqvR3BVe3y7-pK7H91v-3GUJZNn-zj8UAPI9hblpJxksyLdg7J6JuPwiPUY4Zk35tquFeoFjFWA_EkFROyJt0SdKymNH6qX9sAKpwPfDR-aySmBMOgcSIDnO0CwqN4rw8XsQprV3p2CWxaB10-LCpfmHuUhJtdf4NGXlOGDEy4Qtii9YYtXYVkO2U3FWSIwVHCZhoJ2D3ZkYQGsgvcULNJS1yPE0IO1ZJw3GhgepVQ5arDl_v0xI7NeTRHl54exjfFpEzQ0gOTw

###

GET http://localhost:8080/producto
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqYXNvbi5ndWVycmEyNTNAZ21haWwuY29tIiwic2NvcGUiOiJVU0VSIiwiaXNzIjoiIiwiZXhwIjoxNzQyNTIwMTg2LCJpYXQiOjE3NDI1MTY1ODYsInVzZXJuYW1lIjoiamFzb24uZ3VlcnJhMjUzQGdtYWlsLmNvbSJ9.SG-ET37NAhR4_B440BJZkMoowIepp208gpF4qRCBO3rSTvlH9L8XRIb6ARi4aut7QN3P1nnXSQz8DX-G7IzqpLDvSgnmPs8aaj1XDrkK0nHvDddYjWOaFvhF2-Bs4DAvSJoH2PyXpjjDaX7GkG8cGIyvtJOnzRvjm5UEtmON-XNbU1wnxI53cEpJ65poHdZOjLiO6iohM9q21ap7-jm5kd4nzILu5AcYz7chsVIO0PHLvRPaOAgnj6zvNFKqMOwSD26lge6zlAYLtBBQMcaBB6Img3WsZgZAWTGXJUt-_yxiIcHEor1G9FU9jX2t7AqrX9wbs32xZKi_XSbB4wSPpw


###

POST http://localhost:8080/producto
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqYXNvbi5ndWVycmEyNTNAZ21haWwuY29tIiwic2NvcGUiOiJVU0VSIiwiaXNzIjoiIiwiZXhwIjoxNzQyNTM2ODY2LCJpYXQiOjE3NDI1MzMyNjYsInVzZXJuYW1lIjoiamFzb24uZ3VlcnJhMjUzQGdtYWlsLmNvbSJ9.gQCUN_d3Jcq5f-lsvZGJpr9TYjFvjFP6dgn382sEGZLPJ9Bj_sYuaJCGWd_iAwm3D55zy0LHD_EPKEoBOB2jm37TPuy-axeRYRZ2Mnp7C2lEJAZktzeeXw4KCWwjMu2eSST-6QcKNuQH8wskClmrLGOCwBGvNmWrw2YgjfHyCLDY_cPKqksGTE0aQPz8nGunYchNCDj8P32MYu-9uWPOqhKJnFZTmNJNtYa7WEdDo7CYCDhaFKT3OTlHqUPOevJsG0wBMnYBb81Ad8b341p5degBCONL6rUZ1aa2FPVQk1s3ZOO4S43b8zBS2QZzKK66WmypbVFoF6L3yHAVdtIFbA
Content-Type: application/json

{
    "nombre": "hola",
    "descripcion": "Descripcion descripcion pruebas",
    "precio": 200.00,
    "stock": 20,
    "idTipoProducto": 2
}


###

PUT http://localhost:8080/producto/2
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqYXNvbi5ndWVycmEyNTNAZ21haWwuY29tIiwic2NvcGUiOiJVU0VSIiwiaXNzIjoiIiwiZXhwIjoxNzQyNTIwMTg2LCJpYXQiOjE3NDI1MTY1ODYsInVzZXJuYW1lIjoiamFzb24uZ3VlcnJhMjUzQGdtYWlsLmNvbSJ9.SG-ET37NAhR4_B440BJZkMoowIepp208gpF4qRCBO3rSTvlH9L8XRIb6ARi4aut7QN3P1nnXSQz8DX-G7IzqpLDvSgnmPs8aaj1XDrkK0nHvDddYjWOaFvhF2-Bs4DAvSJoH2PyXpjjDaX7GkG8cGIyvtJOnzRvjm5UEtmON-XNbU1wnxI53cEpJ65poHdZOjLiO6iohM9q21ap7-jm5kd4nzILu5AcYz7chsVIO0PHLvRPaOAgnj6zvNFKqMOwSD26lge6zlAYLtBBQMcaBB6Img3WsZgZAWTGXJUt-_yxiIcHEor1G9FU9jX2t7AqrX9wbs32xZKi_XSbB4wSPpw
Content-Type: application/json

{
    "nombre": "Producto 2",
    "descripcion": "Descripcion del producto ha sido actualizada",
    "precio": 120.00,
    "stock": 12,
    "idTipoProducto": 1
}

###

GET http://localhost:8080/producto/2
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqYXNvbi5ndWVycmEyNTNAZ21haWwuY29tIiwic2NvcGUiOiJVU0VSIiwiaXNzIjoiIiwiZXhwIjoxNzQyNTIwMTg2LCJpYXQiOjE3NDI1MTY1ODYsInVzZXJuYW1lIjoiamFzb24uZ3VlcnJhMjUzQGdtYWlsLmNvbSJ9.SG-ET37NAhR4_B440BJZkMoowIepp208gpF4qRCBO3rSTvlH9L8XRIb6ARi4aut7QN3P1nnXSQz8DX-G7IzqpLDvSgnmPs8aaj1XDrkK0nHvDddYjWOaFvhF2-Bs4DAvSJoH2PyXpjjDaX7GkG8cGIyvtJOnzRvjm5UEtmON-XNbU1wnxI53cEpJ65poHdZOjLiO6iohM9q21ap7-jm5kd4nzILu5AcYz7chsVIO0PHLvRPaOAgnj6zvNFKqMOwSD26lge6zlAYLtBBQMcaBB6Img3WsZgZAWTGXJUt-_yxiIcHEor1G9FU9jX2t7AqrX9wbs32xZKi_XSbB4wSPpw



###
DELETE http://localhost:8080/producto/1
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqYXNvbi5ndWVycmEyNTNAZ21haWwuY29tIiwic2NvcGUiOiJVU0VSIiwiaXNzIjoiIiwiZXhwIjoxNzQyNTIwMTg2LCJpYXQiOjE3NDI1MTY1ODYsInVzZXJuYW1lIjoiamFzb24uZ3VlcnJhMjUzQGdtYWlsLmNvbSJ9.SG-ET37NAhR4_B440BJZkMoowIepp208gpF4qRCBO3rSTvlH9L8XRIb6ARi4aut7QN3P1nnXSQz8DX-G7IzqpLDvSgnmPs8aaj1XDrkK0nHvDddYjWOaFvhF2-Bs4DAvSJoH2PyXpjjDaX7GkG8cGIyvtJOnzRvjm5UEtmON-XNbU1wnxI53cEpJ65poHdZOjLiO6iohM9q21ap7-jm5kd4nzILu5AcYz7chsVIO0PHLvRPaOAgnj6zvNFKqMOwSD26lge6zlAYLtBBQMcaBB6Img3WsZgZAWTGXJUt-_yxiIcHEor1G9FU9jX2t7AqrX9wbs32xZKi_XSbB4wSPpw