###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "Jason Saul",
    "password": "password",
    "email": "jason.guerra253@gmail.com"
}


###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "password": "password",
    "username": "jason.guerra253@gmail.com"
}


### 
GET http://localhost:8080/tipoProducto
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqYXNvbi5ndWVycmEyNTNAZ21haWwuY29tIiwic2NvcGUiOiJVU0VSIiwiaXNzIjoiIiwiZXhwIjoxNzQyNTE1NjA0LCJpYXQiOjE3NDI1MTIwMDQsInVzZXJuYW1lIjoiamFzb24uZ3VlcnJhMjUzQGdtYWlsLmNvbSJ9.Q095K_eJwrMzjBWoGrV7CFNhXUcot4nopiosm-pl0HPESWrZlZezFEXM0jnpoWFcl1JyEfK3w25VA5vyjJOZCfFxhH115JKvivMuEpRkVZ3ANiX6wI93mXSG5_OZhxNXDbI7qe35tOGTsLYN0XF2UCeA1QArFfdS3UfOLmbluanwRP6Og0NCrrZQ0IVDJM9HFydzJZzMU1pQT3xsUzN1VjfVOKrfe-jWiXuFcid1-dxV7O5RHt5pGISOspp_igpyW2tr0Y_2v45Oh22vB6BnIRrPzc9Mpj7BfYHQnaeTS1M8x8ytHF9p6eqbrCtci9gdpTKsloxrAnuaelnzMlc12g

###

GET http://localhost:8080/producto
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqYXNvbi5ndWVycmEyNTNAZ21haWwuY29tIiwic2NvcGUiOiJVU0VSIiwiaXNzIjoiIiwiZXhwIjoxNzQyNTE1NjA0LCJpYXQiOjE3NDI1MTIwMDQsInVzZXJuYW1lIjoiamFzb24uZ3VlcnJhMjUzQGdtYWlsLmNvbSJ9.Q095K_eJwrMzjBWoGrV7CFNhXUcot4nopiosm-pl0HPESWrZlZezFEXM0jnpoWFcl1JyEfK3w25VA5vyjJOZCfFxhH115JKvivMuEpRkVZ3ANiX6wI93mXSG5_OZhxNXDbI7qe35tOGTsLYN0XF2UCeA1QArFfdS3UfOLmbluanwRP6Og0NCrrZQ0IVDJM9HFydzJZzMU1pQT3xsUzN1VjfVOKrfe-jWiXuFcid1-dxV7O5RHt5pGISOspp_igpyW2tr0Y_2v45Oh22vB6BnIRrPzc9Mpj7BfYHQnaeTS1M8x8ytHF9p6eqbrCtci9gdpTKsloxrAnuaelnzMlc12g


###

POST http://localhost:8080/producto
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqYXNvbi5ndWVycmEyNTNAZ21haWwuY29tIiwic2NvcGUiOiJVU0VSIiwiaXNzIjoiIiwiZXhwIjoxNzQyNTE1NjA0LCJpYXQiOjE3NDI1MTIwMDQsInVzZXJuYW1lIjoiamFzb24uZ3VlcnJhMjUzQGdtYWlsLmNvbSJ9.Q095K_eJwrMzjBWoGrV7CFNhXUcot4nopiosm-pl0HPESWrZlZezFEXM0jnpoWFcl1JyEfK3w25VA5vyjJOZCfFxhH115JKvivMuEpRkVZ3ANiX6wI93mXSG5_OZhxNXDbI7qe35tOGTsLYN0XF2UCeA1QArFfdS3UfOLmbluanwRP6Og0NCrrZQ0IVDJM9HFydzJZzMU1pQT3xsUzN1VjfVOKrfe-jWiXuFcid1-dxV7O5RHt5pGISOspp_igpyW2tr0Y_2v45Oh22vB6BnIRrPzc9Mpj7BfYHQnaeTS1M8x8ytHF9p6eqbrCtci9gdpTKsloxrAnuaelnzMlc12g
Content-Type: application/json

{
    "nombre": "Producto 1",
    "descripcion": "Descripcion del producto 1",
    "precio": 100.00,
    "stock": 10,
    "idTipoProducto": 1
}


###

PUT http://localhost:8080/producto/1
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqYXNvbi5ndWVycmEyNTNAZ21haWwuY29tIiwic2NvcGUiOiJVU0VSIiwiaXNzIjoiIiwiZXhwIjoxNzQyNTE1NjA0LCJpYXQiOjE3NDI1MTIwMDQsInVzZXJuYW1lIjoiamFzb24uZ3VlcnJhMjUzQGdtYWlsLmNvbSJ9.Q095K_eJwrMzjBWoGrV7CFNhXUcot4nopiosm-pl0HPESWrZlZezFEXM0jnpoWFcl1JyEfK3w25VA5vyjJOZCfFxhH115JKvivMuEpRkVZ3ANiX6wI93mXSG5_OZhxNXDbI7qe35tOGTsLYN0XF2UCeA1QArFfdS3UfOLmbluanwRP6Og0NCrrZQ0IVDJM9HFydzJZzMU1pQT3xsUzN1VjfVOKrfe-jWiXuFcid1-dxV7O5RHt5pGISOspp_igpyW2tr0Y_2v45Oh22vB6BnIRrPzc9Mpj7BfYHQnaeTS1M8x8ytHF9p6eqbrCtci9gdpTKsloxrAnuaelnzMlc12g
Content-Type: application/json

{
    "nombre": "Producto 2",
    "descripcion": "Descripcion del producto 2",
    "precio": 120.00,
    "stock": 12,
    "idTipoProducto": 1
}

###

GET http://localhost:8080/producto/1
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqYXNvbi5ndWVycmEyNTNAZ21haWwuY29tIiwic2NvcGUiOiJVU0VSIiwiaXNzIjoiIiwiZXhwIjoxNzQyNTE1NjA0LCJpYXQiOjE3NDI1MTIwMDQsInVzZXJuYW1lIjoiamFzb24uZ3VlcnJhMjUzQGdtYWlsLmNvbSJ9.Q095K_eJwrMzjBWoGrV7CFNhXUcot4nopiosm-pl0HPESWrZlZezFEXM0jnpoWFcl1JyEfK3w25VA5vyjJOZCfFxhH115JKvivMuEpRkVZ3ANiX6wI93mXSG5_OZhxNXDbI7qe35tOGTsLYN0XF2UCeA1QArFfdS3UfOLmbluanwRP6Og0NCrrZQ0IVDJM9HFydzJZzMU1pQT3xsUzN1VjfVOKrfe-jWiXuFcid1-dxV7O5RHt5pGISOspp_igpyW2tr0Y_2v45Oh22vB6BnIRrPzc9Mpj7BfYHQnaeTS1M8x8ytHF9p6eqbrCtci9gdpTKsloxrAnuaelnzMlc12g


###
DELETE http://localhost:8080/producto/1
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqYXNvbi5ndWVycmEyNTNAZ21haWwuY29tIiwic2NvcGUiOiJVU0VSIiwiaXNzIjoiIiwiZXhwIjoxNzQyNTE1NjA0LCJpYXQiOjE3NDI1MTIwMDQsInVzZXJuYW1lIjoiamFzb24uZ3VlcnJhMjUzQGdtYWlsLmNvbSJ9.Q095K_eJwrMzjBWoGrV7CFNhXUcot4nopiosm-pl0HPESWrZlZezFEXM0jnpoWFcl1JyEfK3w25VA5vyjJOZCfFxhH115JKvivMuEpRkVZ3ANiX6wI93mXSG5_OZhxNXDbI7qe35tOGTsLYN0XF2UCeA1QArFfdS3UfOLmbluanwRP6Og0NCrrZQ0IVDJM9HFydzJZzMU1pQT3xsUzN1VjfVOKrfe-jWiXuFcid1-dxV7O5RHt5pGISOspp_igpyW2tr0Y_2v45Oh22vB6BnIRrPzc9Mpj7BfYHQnaeTS1M8x8ytHF9p6eqbrCtci9gdpTKsloxrAnuaelnzMlc12g