###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "Jason Saul",
    "password": "password",
    "email": "jason.guerra253@gmail.com"
}


###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "password": "password",
    "username": "jason.guerra253@gmail.com"
}


### 
GET http://localhost:8080/tipoProducto
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqYXNvbi5ndWVycmEyNTNAZ21haWwuY29tIiwic2NvcGUiOiJVU0VSIiwiaXNzIjoiIiwiZXhwIjoxNzQyNTIwMTg2LCJpYXQiOjE3NDI1MTY1ODYsInVzZXJuYW1lIjoiamFzb24uZ3VlcnJhMjUzQGdtYWlsLmNvbSJ9.SG-ET37NAhR4_B440BJZkMoowIepp208gpF4qRCBO3rSTvlH9L8XRIb6ARi4aut7QN3P1nnXSQz8DX-G7IzqpLDvSgnmPs8aaj1XDrkK0nHvDddYjWOaFvhF2-Bs4DAvSJoH2PyXpjjDaX7GkG8cGIyvtJOnzRvjm5UEtmON-XNbU1wnxI53cEpJ65poHdZOjLiO6iohM9q21ap7-jm5kd4nzILu5AcYz7chsVIO0PHLvRPaOAgnj6zvNFKqMOwSD26lge6zlAYLtBBQMcaBB6Img3WsZgZAWTGXJUt-_yxiIcHEor1G9FU9jX2t7AqrX9wbs32xZKi_XSbB4wSPpw

###

GET http://localhost:8080/producto
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqYXNvbi5ndWVycmEyNTNAZ21haWwuY29tIiwic2NvcGUiOiJVU0VSIiwiaXNzIjoiIiwiZXhwIjoxNzQyNTIwMTg2LCJpYXQiOjE3NDI1MTY1ODYsInVzZXJuYW1lIjoiamFzb24uZ3VlcnJhMjUzQGdtYWlsLmNvbSJ9.SG-ET37NAhR4_B440BJZkMoowIepp208gpF4qRCBO3rSTvlH9L8XRIb6ARi4aut7QN3P1nnXSQz8DX-G7IzqpLDvSgnmPs8aaj1XDrkK0nHvDddYjWOaFvhF2-Bs4DAvSJoH2PyXpjjDaX7GkG8cGIyvtJOnzRvjm5UEtmON-XNbU1wnxI53cEpJ65poHdZOjLiO6iohM9q21ap7-jm5kd4nzILu5AcYz7chsVIO0PHLvRPaOAgnj6zvNFKqMOwSD26lge6zlAYLtBBQMcaBB6Img3WsZgZAWTGXJUt-_yxiIcHEor1G9FU9jX2t7AqrX9wbs32xZKi_XSbB4wSPpw


###

POST http://localhost:8080/producto
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqYXNvbi5ndWVycmEyNTNAZ21haWwuY29tIiwic2NvcGUiOiJVU0VSIiwiaXNzIjoiIiwiZXhwIjoxNzQyNTIwMTg2LCJpYXQiOjE3NDI1MTY1ODYsInVzZXJuYW1lIjoiamFzb24uZ3VlcnJhMjUzQGdtYWlsLmNvbSJ9.SG-ET37NAhR4_B440BJZkMoowIepp208gpF4qRCBO3rSTvlH9L8XRIb6ARi4aut7QN3P1nnXSQz8DX-G7IzqpLDvSgnmPs8aaj1XDrkK0nHvDddYjWOaFvhF2-Bs4DAvSJoH2PyXpjjDaX7GkG8cGIyvtJOnzRvjm5UEtmON-XNbU1wnxI53cEpJ65poHdZOjLiO6iohM9q21ap7-jm5kd4nzILu5AcYz7chsVIO0PHLvRPaOAgnj6zvNFKqMOwSD26lge6zlAYLtBBQMcaBB6Img3WsZgZAWTGXJUt-_yxiIcHEor1G9FU9jX2t7AqrX9wbs32xZKi_XSbB4wSPpw
Content-Type: application/json

{
    "nombre": "Producto nuevo pruebas",
    "descripcion": "Descripcion descripcion pruebas",
    "precio": 200.00,
    "stock": 20,
    "idTipoProducto": 2
}


###

PUT http://localhost:8080/producto/2
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqYXNvbi5ndWVycmEyNTNAZ21haWwuY29tIiwic2NvcGUiOiJVU0VSIiwiaXNzIjoiIiwiZXhwIjoxNzQyNTIwMTg2LCJpYXQiOjE3NDI1MTY1ODYsInVzZXJuYW1lIjoiamFzb24uZ3VlcnJhMjUzQGdtYWlsLmNvbSJ9.SG-ET37NAhR4_B440BJZkMoowIepp208gpF4qRCBO3rSTvlH9L8XRIb6ARi4aut7QN3P1nnXSQz8DX-G7IzqpLDvSgnmPs8aaj1XDrkK0nHvDddYjWOaFvhF2-Bs4DAvSJoH2PyXpjjDaX7GkG8cGIyvtJOnzRvjm5UEtmON-XNbU1wnxI53cEpJ65poHdZOjLiO6iohM9q21ap7-jm5kd4nzILu5AcYz7chsVIO0PHLvRPaOAgnj6zvNFKqMOwSD26lge6zlAYLtBBQMcaBB6Img3WsZgZAWTGXJUt-_yxiIcHEor1G9FU9jX2t7AqrX9wbs32xZKi_XSbB4wSPpw
Content-Type: application/json

{
    "nombre": "Producto 2",
    "descripcion": "Descripcion del producto ha sido actualizada",
    "precio": 120.00,
    "stock": 12,
    "idTipoProducto": 1
}

###

GET http://localhost:8080/producto/2
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqYXNvbi5ndWVycmEyNTNAZ21haWwuY29tIiwic2NvcGUiOiJVU0VSIiwiaXNzIjoiIiwiZXhwIjoxNzQyNTIwMTg2LCJpYXQiOjE3NDI1MTY1ODYsInVzZXJuYW1lIjoiamFzb24uZ3VlcnJhMjUzQGdtYWlsLmNvbSJ9.SG-ET37NAhR4_B440BJZkMoowIepp208gpF4qRCBO3rSTvlH9L8XRIb6ARi4aut7QN3P1nnXSQz8DX-G7IzqpLDvSgnmPs8aaj1XDrkK0nHvDddYjWOaFvhF2-Bs4DAvSJoH2PyXpjjDaX7GkG8cGIyvtJOnzRvjm5UEtmON-XNbU1wnxI53cEpJ65poHdZOjLiO6iohM9q21ap7-jm5kd4nzILu5AcYz7chsVIO0PHLvRPaOAgnj6zvNFKqMOwSD26lge6zlAYLtBBQMcaBB6Img3WsZgZAWTGXJUt-_yxiIcHEor1G9FU9jX2t7AqrX9wbs32xZKi_XSbB4wSPpw



###
DELETE http://localhost:8080/producto/1
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqYXNvbi5ndWVycmEyNTNAZ21haWwuY29tIiwic2NvcGUiOiJVU0VSIiwiaXNzIjoiIiwiZXhwIjoxNzQyNTIwMTg2LCJpYXQiOjE3NDI1MTY1ODYsInVzZXJuYW1lIjoiamFzb24uZ3VlcnJhMjUzQGdtYWlsLmNvbSJ9.SG-ET37NAhR4_B440BJZkMoowIepp208gpF4qRCBO3rSTvlH9L8XRIb6ARi4aut7QN3P1nnXSQz8DX-G7IzqpLDvSgnmPs8aaj1XDrkK0nHvDddYjWOaFvhF2-Bs4DAvSJoH2PyXpjjDaX7GkG8cGIyvtJOnzRvjm5UEtmON-XNbU1wnxI53cEpJ65poHdZOjLiO6iohM9q21ap7-jm5kd4nzILu5AcYz7chsVIO0PHLvRPaOAgnj6zvNFKqMOwSD26lge6zlAYLtBBQMcaBB6Img3WsZgZAWTGXJUt-_yxiIcHEor1G9FU9jX2t7AqrX9wbs32xZKi_XSbB4wSPpw