spring:
    application:
        name: pruebatecnica
    datasource:
        url: jdbc:sqlserver://localhost:1434;trustServerCertificate=true;databaseName=pruebatecnica
        username: sa
        password: MiPassword123

jwt:
  private.key: classpath:private.key
  public.key: classpath:public.key
  duration: 3600
app:
  url: http://localhost:8080
  cors: http://localhost:4200


